spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - openid
        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
